import type { Metadata } from "next";
import "./globals.css";
import { NavMenu } from "@/components/shared/Nav";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen">
        <Providers>
          <NavMenu />
          <main className="flex-grow flex flex-col items-center justify-center">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
