import type { Metadata } from "next";
import "./globals.css";
import { NavMenu } from "@/components/shared/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavMenu />
      <body className="antialiased">{children}</body>
    </html>
  );
}
